services:
  devcontainer:
    build:
      context: devcontainer/
      dockerfile: dockerfile
    shm_size: 256m # GUI用に共有メモリ拡張
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces:cached
    hostname: devcontainer
    networks:
      - ros_nw
  ros_server:
    build:
      context: devcontainer/
      dockerfile: dockerfile
    shm_size: 256m # GUI用に共有メモリ拡張
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces:cached
    hostname: ros_server
    networks:
      - ros_nw
  db:
    build:
      context: db
      dockerfile: Dockerfile
    restart: always
    hostname: database
    networks:
      - ros_nw
    volumes:
      - type: bind
        source: db/initdb
        target: /docker-entrypoint-initdb.d
    ports:
      - target: 5432
        published: 5432
    stdin_open: false
    tty: false
networks:
  ros_nw:
