services:
  devcontainer:
    build:
      context: devcontainer/
      dockerfile: dockerfile
    shm_size: 256m # GUI用に共有メモリ拡張
    stdin_open: true
    tty: true
    volumes:
      - .:/workspaces:cached
    hostname: devcontainer
    networks:
      - ros_nw

networks:
  ros_nw:
    external: false
    ipam:
      driver: default
      config:
        - subnet: 10.20.0.0/16
