FROM mcr.microsoft.com/devcontainers/cpp:ubuntu-24.04

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN echo "UPDATE REPOSITORY IN JAPAN"
ARG OLD_ARCHIVE_URL=http://archive.ubuntu.com/ubuntu/
ARG NEW_ARCHIVE_URL=http://ftp.jaist.ac.jp/pub/Linux/ubuntu/
RUN sed -i "s@${OLD_ARCHIVE_URL}@${NEW_ARCHIVE_URL}@g" /etc/apt/sources.list.d/ubuntu.sources

RUN echo "INSTALL BASE TOOLS"
RUN apt-get -qq update &&\
    DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    ## utils
    sudo\
    # for add-apt-repository
    software-properties-common\
    ## network tools
    curl\
    wget

RUN echo "INSTALL DOCKER"
ARG DOCKER_GID
RUN groupadd docker -g ${DOCKER_GID}
ENV DOCKER_KEYRING_URL=https://download.docker.com/linux/ubuntu/gpg
ENV DOCKER_KEYRING_PATH=/etc/apt/keyrings/docker.asc
ENV DOCKER_URI=https://download.docker.com/linux/ubuntu
RUN CPU_ARCH=$(dpkg --print-architecture) &&\
    VERSION_CODENAME=$(. /etc/os-release && echo ${VERSION_CODENAME}) &&\
    curl -fsSL ${DOCKER_KEYRING_URL} -o ${DOCKER_KEYRING_PATH} &&\
    echo "deb [arch=${CPU_ARCH} signed-by=${DOCKER_KEYRING_PATH}] ${DOCKER_URI} ${VERSION_CODENAME} stable" >/etc/apt/sources.list.d/docker.list
RUN apt-get -qq update &&\
    DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    docker-ce\
    docker-ce-cli\
    containerd.io\
    docker-buildx-plugin\
    docker-compose-plugin


RUN echo "INSTALL ROS PACKAGES"
# add ros package repository
ENV ROS_DISTRO=jazzy
ARG ROS_KEYRING_URL=https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
ARG ROS_KEYRING_PATH=/usr/share/keyrings/ros-archive-keyring.gpg
ARG ROS_URI=http://packages.ros.org/ros2/ubuntu
RUN CPU_ARCH=$(dpkg --print-architecture) &&\
    VERSION_CODENAME=$(. /etc/os-release && echo ${VERSION_CODENAME}) &&\
    add-apt-repository -y universe &&\
    curl -sL ${ROS_KEYRING_URL} -o ${ROS_KEYRING_PATH} &&\
    echo "deb [arch=${CPU_ARCH} signed-by=${ROS_KEYRING_PATH}] ${ROS_URI} ${VERSION_CODENAME} main" > /etc/apt/sources.list.d/ros2.list
RUN apt-get -qq update &&\
    DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    ros-dev-tools\
    ros-${ROS_DISTRO}-desktop\
    python3-argcomplete\
    python3-colcon-common-extensions\
    python3-colcon-clean\
    python3-rosdep

RUN echo "INSTALL C++ TOOLS"
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    ## C++
    build-essential cmake gdb\
    libgtest-dev\
    libpqxx-dev\
    nlohmann-json3-dev\
    # clang
    clang\
    clang-format\
    clang-tools\
    # static analysis
    cppcheck\
    clang-tidy\
    bear

RUN echo "INSTALL UTILITIES"
RUN DEBIAN_FRONTEND=noninteractive apt-get -qq install --no-install-recommends -y\
    ## util
    ca-certificates libssl-dev\
    locales\
    less\
    silversearcher-ag\
    peco\
    git\
    vim\
    ## network tools
    lsof\
    ncat\
    nmap\
    dnsutils\
    iproute2\
    iputils-ping\
    traceroute\
    ## postgres
    postgresql-client\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/*

# setting locale
ENV LANG=ja_JP.UTF-8
RUN locale-gen ja_JP ja_JP.UTF-8 &&\
    update-locale LC_ALL=ja_JP.UTF-8 LANG=ja_JP.UTF-8 &&\
    locale

## /etc/ros/rosdep/sources.list.d/にリポジトリリストを構築
RUN rosdep init
## DL系コマンドはイメージが重くなるので使わない
# RUN rosdep update

# install hadolint
ARG HADOLINT_URL=https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
ARG HADOLINT_PATH=/usr/local/bin/hadolint
RUN curl -sL --insecure ${HADOLINT_URL} -o ${HADOLINT_PATH} &&\
    chmod +x ${HADOLINT_PATH}

WORKDIR /etc/bash_completion.d
RUN docker completion bash > docker-completion

WORKDIR /etc/profile.d
RUN {\
    echo "export PGHOST=database";\
    echo "export PGPORT=5432";\
    echo "export PGUSER=postgres";\
    echo "export PGDATABASE=postgres";\
    } >> postgres.sh
RUN {\
    echo "source /opt/ros/${ROS_DISTRO}/setup.bash";\
    } >> ros.sh
RUN {\
    # pecoのバグ回避策（https://github.com/peco/peco/issues/541）
    echo "export TERM=xterm";\
    } >> peco.sh

# user definition
ENV USER=vscode
ENV SHELL=/bin/bash
RUN usermod -aG sudo ${USER} &&\
    usermod -aG docker ${USER}

USER 1000
WORKDIR $HOME/bin
COPY diff-highlight .
